# 训练参数
use_cuda: false      # 是否使用GPU
batch_size: 2       # 小批次数据量
epochs: 1000         # 最大训练循环
stop_iou: 0.9       # 当iou达到该值时停止训练
data_path: "./data" # 数据存放目录 该目录下应有train和eval子目录
save_model_path: "./model"    # 模型保存路径
save_point_path: "./model"    # 存档点保存路径
load_point_path: "./model/train_od_3"    # 存档点读取路径
ori_img_size:       # 输入图像尺寸
  - 1200
  - 2448
ipt_img_size:       # 进入网络时的尺寸
  - 1200            # H
  - 1200             # W
e_learning_rate: 0.1       # 初始学习率

# 输出参数
print_epoch_interval: 1       # 间隔多少Epoch输出一次信息