###                                   ###
#-- 网络配置文件 请参考网络配置文档进行修改 --#
###                                   ###

# 基础配置
classify_num: 4     # 分类数
base_size: 300      # Reader返回的图像尺寸

# 性能配置 - 目标检测
min_ratio: 3        # 先验框的长度和 base_size 的最小比率
max_ratio: 50       # 先验框的长度和 base_size 的最大比率
aspect_ratios:      # 候选框的宽高比， aspect_ratios 和 input 的个数必须相等。如果每个特征层提取先验框的 aspect_ratio 多余一个，写成嵌套的list，例如[[2., 3.]]。
  - - 1.
  - - 1.
    - 2.
  - - 1.
    - 3.

offset: 0.5         # 左上角先验框中心在水平和垂直方向上的偏移
nms_threshold: 0.45 # NMS阈值
background_label: -1 # 背景标签，若为-1则考虑所有标签

# 性能配置 - 一阶段分类任务
deep_level: 2       # 网络深度控制
ipt_size_level: 8    # 图片尺寸级别
classify_level: 3    # 分类网络级别

# 评估配置

overlap_threshold: 0.5    # 判断真假阳性的阈值，默认为0.5
ap_version: '11point'     # 平均精度的计算方法，必须是 "integral" 或 "11point"

